# MD5: 4058204573f29f4be1e7f125a542ce8d
CFG_FEATURE_AT_NV_WRITE_SUPPORT                 := YES
CFG_FEATURE_READ_LOG_FILTER_CFG                 := YES
CFG_FEATURE_MEMCPY_REBOOT_CFG                   := FEATURE_ON
CFG_FEATURE_PHONE_ENG_AT_CMD                    := FEATURE_ON
